export enum HVACContrMode {
    Auto = 0,
    Heat = 1,
    MorningWarmup = 2,
    Cool = 3,
    NightPurge = 4,
    Precool = 5,
    Off = 6,
    Test = 7,
    EmergencyHeat = 8,
    FanOnly = 9,
    FreeCool = 10,
    Ice = 11,
    MaximumHeatingMode = 12,
    EconomicMode = 13,
    Dehumidification = 14,
    CalibrationMode = 15,
    EmergencyCoolMode = 16,
    EmergencySteamMode = 17,
    NoDem = 20
}
