export enum KnxConnectionType {
    DEVICE_MGMT_CONNECTION = 0x03,
    TUNNEL_CONNECTION = 0x04,
    REMOTE_LOGGING_CONNECTION = 0x06,
    REMOTE_CONFIGURATION_CONNECTION = 0x07,
    OBJECT_SERVER_CONNECTION = 0x08,
}
